### PR TITLE
fix behavior with strict mode

### LINKED ISSUE #5: [BUG]: fetch twice with React.StrictMode
ScreenShot 2024-01-06 21 04 18

https://codesandbox.io/p/sandbox/suspicious-archimedes-t8qhly

### PR DESCRIPTION
**Pull request by dai-shi**
close #5

### CODE REVIEW

File: src/atomWithCache.ts [hunk 1]
```diff
@@ -29,27 +29,24 @@ export function atomWithCache<Value>(
     writeGetterAtom.debugPrivate = true;
```
Comment (hyoban) [inline src/atomWithCache.ts:29]: remove useless writeGetterAtom

Comment (dai-shi) [reply src/atomWithCache.ts:29]: Ah, nice catch.
